"""изменение note

Revision ID: 020f658f272a
Revises: b391366726a7
Create Date: 2024-04-11 13:07:53.879975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020f658f272a'
down_revision = 'b391366726a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))
        batch_op.drop_column('private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
