"""Add note field to grades table

Revision ID: 406220c7ddbf
Revises: 78efc1337474
Create Date: 2024-04-10 13:54:24.366157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406220c7ddbf'
down_revision = '78efc1337474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
